### ISSUE TITLE
Indicator of Pollution/emissions

### ISSUE THREAD

**Issue by ciupava** [ciupava/LandUseDemonstrator#2]
This issue is meant to help tracking the process of searching, selecting and generating the relevant explanatory variables (land use features) for modelling emissions as a key indicator.

**Comment by darribas** [comment]
After discussing this w/ Ali Ford (Newcastle), I'm starting to veer towards using some measure of air quality/pollution, relying on the Urban Observatory. This would take it away from the emissions focus, but would have other benefits.

**Comment by ciupava** [comment]
**Air quality data for UK**

UK map
- NAEI BEIS https://naei.beis.gov.uk/emissionsapp/
- Defra https://uk-air.defra.gov.uk/data/gis-mapping/

Data gov uk
- Air quality statistics https://www.gov.uk/government/statistical-data-sets/env02-air-quality-statistics
<img width="683" alt="image" src="https://user-images.githubusercontent.com/3450313/211805708-78b06781-1266-4f3c-b560-f1d6cc8ce0d8.png">*example of the data available for NO2*
Note: the data is at monitoring sites level (one row per site)

general information here https://www.gov.uk/government/collections/air-quality-and-emissions-statistics

**Comment by martinfleis** [comment]
I was exploring the data from the urban observatory and there's a bit of a coverage issue. What looks like a decent mesh of sensors here https://newcastle.urbanobservatory.ac.uk turns out to be less impressive when you filter for those measuring air quality. You can check the map on the bottom of [this notebook](https://nbviewer.org/github/martinfleis/LandUseDemonstrator/blob/indicators/python/air_quality.ipynb) to see for yourself. Notice the boundary of the area of interest in black. We would get in a lot of trouble trying to interpolate anything south of the river.

**Comment by martinfleis** [comment]
One idea you may have discussed (or partially).

UK AIR data (linked above) contains 1km grid data for selected emissions. If we want to combine them to a single air quality index, we may build the expert model based on the methodology EEA is using for the European air quality index described [here](https://airindex.eea.europa.eu/Map/AQI/Viewer/#). That is based on the relative risks associated to short-term exposure to PM2.5, O3 and NO2, as defined by the World Health Organization in its report on the Health Risks of Air Pollution in Europe project ([HRAPIE project report](http://www.euro.who.int/en/health-topics/environment-and-health/air-quality/publications/2013/health-risks-of-air-pollution-in-europe-hrapie-project.-recommendations-for-concentrationresponse-functions-for-costbenefit-analysis-of-particulate-matter,-ozone-and-nitrogen-dioxide)). That would have a direct interpretation regarding health hazards, better than some raw metrics.

**Comment by martinfleis** [comment]
I tried to do the derived index as mentioned above, it is shown and documented [here](https://nbviewer.org/github/martinfleis/LandUseDemonstrator/blob/indicators/python/air_quality.ipynb) (rendering from my branch, linking nbviewer to see leaflet map)
