### ISSUE TITLE
Indicator of House prices

### ISSUE THREAD

**Issue by ciupava** [ciupava/LandUseDemonstrator#3]
This issue is meant to help tracking the process of searching, selecting and generating the relevant explanatory variables (land use features) for modelling house prices as a key indicator.

**Comment by ciupava** [comment]
@martinfleis some infos I have collected for data for this indicator are here
https://ciupava.github.io/LandUseDemonstrator/notes.html#house-prices-indicator

**Comment by martinfleis** [comment]
Current notebook mostly leaning towards the same conclusions that are in the notes https://github.com/martinfleis/LandUseDemonstrator/blob/indicators/python/house_prices.ipynb

**Comment by martinfleis** [comment]
https://reshare.ukdataservice.ac.uk/854942/

**Comment by martinfleis** [comment]
We now have price per sqm per OA. See https://github.com/ciupava/LandUseDemonstrator/blob/main/python/house_prices.ipynb
