### ISSUE TITLE
Indicator of Job accessibility

### ISSUE THREAD

**Issue by ciupava** [ciupava/LandUseDemonstrator#4]
This issue is meant to help tracking the process of searching, selecting and generating the relevant explanatory variables (land use features) for modelling job accessibility as a key indicator.

**Comment by ciupava** [comment]
Jonathan Levine, Joe Grengs, Qingyun Shen & Qing Shen (2012) _Does Accessibility Require Density or Speed?_, Journal of the American Planning Association, 78:2, 157-172, DOI: [10.1080/01944363.2012.677119](https://doi.org/10.1080/01944363.2012.677119)

> But mobility and proximity exist in tension with each other: Places with many origins and destinations near one another tend to be places where surface transportation is slow; conversely, areas of rapid surface travel tend to be areas where origins and destinations are further apart. It is not immediately apparent which urban forms offer higher accessibility: areas of rapid surface travel and little proximity, or areas offering
high proximity of origins and destinations but slower travel

**Comment by martinfleis** [comment]
This may be relevant https://twitter.com/UrbanDemog/status/1615736071459069952

**Comment by ciupava** [comment]
was watching it today!
