### ISSUE TITLE
Use github actions for auto-generating rendered docs

### ISSUE THREAD

**Issue by dabreegster** [ciupava/LandUseDemonstrator#6]
Looks like you're currently running `quarto build` or so manually and checking the results into this git repo. There's an easier way -- you just commit the quarto markdown (and images and such), and use github actions to automatically rebuild the docs every time you push. https://github.com/dabreegster/talks/blob/main/.github/workflows/pages.yml is an example of how it works. There's also a few github repo settings to click. Next time I'm in the office, we could take a few minutes and set this up?

**Comment by ciupava** [comment]
sounds good, thanks for taking time for this
