### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by darribas** [ciupava/LandUseDemonstrator#8]
Thread to agree on a catchy name.

**Comment by darribas** [comment]
How about Land Use DemOnstrator (aka LUDO)? It's "play" in Latin.

It's also a cool game with some resemblance of land use on the board?!?!

https://en.wikipedia.org/wiki/Ludo

**Comment by ciupava** [comment]
at the moment I was going with LOUD :mega:

see the gh-pages book https://ciupava.github.io/LandUseDemonstrator/
<img width="296" alt="image" src="https://user-images.githubusercontent.com/3450313/206305962-a92c8de6-5eaf-4cde-8086-36656e25b5ae.png">

(it was in my personal notes for today, we ended up not having the team call)

**Comment by ciupava** [comment]
I think we arrived to Demoland as the winner?
Can we announce that? 📣 🎉
